// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxwySnOnLSU-dUj5G5iaGSm-I8WzmW474',
    appId: '1:733010340917:web:3f9530d7275ab97e30957c',
    messagingSenderId: '733010340917',
    projectId: 'flutterfirestore1-f4329',
    authDomain: 'flutterfirestore1-f4329.firebaseapp.com',
    storageBucket: 'flutterfirestore1-f4329.appspot.com',
    measurementId: 'G-KQBWPLTHSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3uJknlaIP8zmW7U9b7sjZ1D3hgqsunI',
    appId: '1:733010340917:android:71d9d55e8770c0f630957c',
    messagingSenderId: '733010340917',
    projectId: 'flutterfirestore1-f4329',
    storageBucket: 'flutterfirestore1-f4329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPYiLybS0SC0gn65e7croxh-Vtv9gwQ_g',
    appId: '1:733010340917:ios:3af4eef8c6d073c230957c',
    messagingSenderId: '733010340917',
    projectId: 'flutterfirestore1-f4329',
    storageBucket: 'flutterfirestore1-f4329.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPYiLybS0SC0gn65e7croxh-Vtv9gwQ_g',
    appId: '1:733010340917:ios:3af4eef8c6d073c230957c',
    messagingSenderId: '733010340917',
    projectId: 'flutterfirestore1-f4329',
    storageBucket: 'flutterfirestore1-f4329.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxwySnOnLSU-dUj5G5iaGSm-I8WzmW474',
    appId: '1:733010340917:web:41bb5d1a1809028c30957c',
    messagingSenderId: '733010340917',
    projectId: 'flutterfirestore1-f4329',
    authDomain: 'flutterfirestore1-f4329.firebaseapp.com',
    storageBucket: 'flutterfirestore1-f4329.appspot.com',
    measurementId: 'G-VPCEL1371X',
  );
}
