// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUwzdUSbEHWqZUtxrkDyoEo_a29Hrw7u8',
    appId: '1:295754063301:web:5a9077122c0ddbd4a23fac',
    messagingSenderId: '295754063301',
    projectId: 'notes-78af3',
    authDomain: 'notes-78af3.firebaseapp.com',
    storageBucket: 'notes-78af3.appspot.com',
    measurementId: 'G-JEJYRDRXHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQm54qIajZryyt_qsPuRw4PORns3rv7g',
    appId: '1:295754063301:android:cb75ec0ad87c4ea9a23fac',
    messagingSenderId: '295754063301',
    projectId: 'notes-78af3',
    storageBucket: 'notes-78af3.appspot.com',
  );
}
