// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fgeBk3HX5H3ANlzbTYeVr1OPOWHFEP0',
    appId: '1:874643391992:web:61127880ded4c862fdc20d',
    messagingSenderId: '874643391992',
    projectId: 'nore-e8321',
    authDomain: 'nore-e8321.firebaseapp.com',
    storageBucket: 'nore-e8321.appspot.com',
    measurementId: 'G-Y1FDGVCR50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxTY88McF2hBVvb1Wri6bHtdExtsfZvrA',
    appId: '1:874643391992:android:bb6a952bf5577587fdc20d',
    messagingSenderId: '874643391992',
    projectId: 'nore-e8321',
    storageBucket: 'nore-e8321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4IBNd7O2_tCGnrkTBvc0hlvzmH3_9Mhc',
    appId: '1:874643391992:ios:4f30f28ce9d960ddfdc20d',
    messagingSenderId: '874643391992',
    projectId: 'nore-e8321',
    storageBucket: 'nore-e8321.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4IBNd7O2_tCGnrkTBvc0hlvzmH3_9Mhc',
    appId: '1:874643391992:ios:4f30f28ce9d960ddfdc20d',
    messagingSenderId: '874643391992',
    projectId: 'nore-e8321',
    storageBucket: 'nore-e8321.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2fgeBk3HX5H3ANlzbTYeVr1OPOWHFEP0',
    appId: '1:874643391992:web:bc7cf8d228297634fdc20d',
    messagingSenderId: '874643391992',
    projectId: 'nore-e8321',
    authDomain: 'nore-e8321.firebaseapp.com',
    storageBucket: 'nore-e8321.appspot.com',
    measurementId: 'G-J3NCLKH5Y8',
  );

}